#%RAML 0.8

title: PhotoBackup
version: v1
traits:
    - secured:
        queryParameters:
            password:
                description: The server password
                required: true
                type: string

/:
    post:
        description: Create a new picture to the collection.
        queryParameters:
            upfile:
                description: The photo to backup
                required: true
                type: file
            filesize:
                description: The size in bytes of the uploaded file.
                required: true
                type: integer
        is: [ secured ]
        body:
        responses:
            200: "Test succeeded \o/"
            403: "wrong password!"
            500: "MEDIA_ROOT does not exist!" or "Can't write to MEDIA_ROOT!"


/test:
    is: [ secured ]
    post:
        description: Create a test result.
        responses:
            200: OK
            400: "missing file size in the request!"
            401: "no file in the request!"
            403: "wrong password!"
            411: "file sizes do not match!"
            500: server error
